### ISSUE TITLE
Consider Removing Watchgod

### ISSUE THREAD

**Issue by hannahhall** [nashville-software-school/bangazon-llc#90]
Switch to only running through debugger

**Comment by JoeShep** [comment]
Is the option of either/both causing confusion for students?

**Comment by stevebrownlee** [comment]
Absolutely

**Comment by hannahhall** [comment]
Yeah students get confused about what watchgod is actually doing and whether watchgod is the server. Then once we have them switch to the debugger it muddies the waters further
